# Generated by Django 2.2.10 on 2020-11-15 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 15, 20, 52, 34, 100220), verbose_name='Дата публикации'),
        ),
    ]
